// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Mirror Next.js behaviour: .env.local overrides .env
// Skip when SKIP_DOTENV_LOCAL=1 (e.g. migrate:prod uses .env directly)
if (!process.env.SKIP_DOTENV_LOCAL) {
  config({ path: ".env.local", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
